<a href="https://colab.research.google.com/github/SuyogPatgave/Python_Codes-Projects/blob/main/CRM_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing library packages

In [110]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Data Import

In [111]:
acc= pd.read_csv('/content/accounts.csv')
data_dic = pd.read_csv('/content/data_dictionary.csv')
prdts = pd.read_csv('/content/products.csv')
sales_pipe = pd.read_csv('/content/sales_pipeline.csv')
sales_team = pd.read_csv('/content/sales_teams.csv')

In [112]:
pd.set_option('display.width', 300)
pd.set_option('display.max_columns', None)

Consolidating all datasets (assigning names for referential convenience) in one list

In [113]:
datasets = [('accounts', acc), ('data dictionary', data_dic), ('products', prdts), ('sales pipeline', sales_pipe), ('sales team', sales_team)]

Data Visibility

In [114]:
for name, dataset in datasets:
  print(f"\n\n\n{name.title()}:")
  print(dataset.head(10))
  print(f"--Dimensions: {dataset.shape}")

Accounts:
            account         sector  year_established  revenue  employees office_location     subsidiary_of
0  Acme Corporation      technolgy              1996  1100.04       2822   United States               NaN
1        Betasoloin        medical              1999   251.41        495   United States               NaN
2          Betatech        medical              1986   647.18       1185           Kenya               NaN
3        Bioholding        medical              2012   587.34       1356      Philipines               NaN
4           Bioplex        medical              1991   326.82       1016   United States               NaN
5          Blackzim         retail              2009   497.11       1588   United States               NaN
6     Bluth Company      technolgy              1993  1242.32       3027   United States  Acme Corporation
7        Bubba Gump       software              2002   987.39       2253   United States               NaN
8           Cancity         retail              2001   718.62       2448   United States               NaN
9            Cheers  entertainment              1993  4269.90       6472   United States   Massive Dynamic
--Dimensions: (85, 7)



Data Dictionary:
      Table             Field                          Description
0  accounts           account                         Company name
1  accounts            sector                             Industry
2  accounts  year_established                     Year Established
3  accounts           revenue  Annual revenue (in millions of USD)
4  accounts         employees                  Number of employees
5  accounts   office_location                         Headquarters
6  accounts     subsidiary_of                       Parent company
7  products           product                         Product name
8  products            series                       Product series
9  products       sales_price               Suggested retail price
--Dimensions: (21, 3)



Products:
          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768
--Dimensions: (7, 3)



Sales Pipeline:
  opportunity_id      sales_agent         product   account deal_stage engage_date  close_date  close_value
0       1C1I7A6R      Moses Frase  GTX Plus Basic   Cancity        Won  2016-10-20  2017-03-01       1054.0
1       Z063OYW0  Darcel Schlecht          GTXPro     Isdom        Won  2016-10-25  2017-03-11       4514.0
2       EC4QE1BX  Darcel Schlecht      MG Special   Cancity        Won  2016-10-25  2017-03-07         50.0
3       MV1LWRNH      Moses Frase       GTX Basic   Codehow        Won  2016-10-25  2017-03-09        588.0
4       PE84CX4O        Zane Levy       GTX Basic    Hatfan        Won  2016-10-25  2017-03-02        517.0
5       ZNBS69V1    Anna Snelling      MG Special  Ron-tech        Won  2016-10-29  2017-03-01         49.0
6       9ME3374G   Vicki Laflamme      MG Special   J-Texon        Won  2016-10-30  2017-03-02         57.0
7       7GN8Q4LL   Markita Hansen       GTX Basic    Cheers        Won  2016-11-01  2017-03-07        601.0
8       OLK9LKZB  Niesha Huffines  GTX Plus Basic  Zumgoity        Won  2016-11-01  2017-03-03       1026.0
9       HAXMC4IX   James Ascencio     MG Advanced       NaN   Engaging  2016-11-03         NaN          NaN
--Dimensions: (8800, 8)



Sales Team:
          sales_agent           manager regional_office
0       Anna Snelling  Dustin Brinkmann         Central
1      Cecily Lampkin  Dustin Brinkmann         Central
2   Versie Hillebrand  Dustin Brinkmann         Central
3     Lajuana Vencill  Dustin Brinkmann         Central
4         Moses Frase  Dustin Brinkmann         Central
5  Jonathan Berthelot     Melvin Marxen         Central
6   Marty Freudenburg     Melvin Marxen         Central
7    Gladys Colclough     Melvin Marxen         Central
8     Niesha Huffines     Melvin Marxen         Central
9     Darcel Schlecht     Melvin Marxen         Central
--Dimensions: (35, 3)

Data Description

In [115]:
  for name, dataset in datasets:
    print(f"\n\n\n{name.title()}:")
    print(dataset.describe())

Accounts:
       year_established       revenue     employees
count         85.000000     85.000000     85.000000
mean        1996.105882   1994.632941   4660.823529
std            8.865427   2169.491436   5715.601198
min         1979.000000      4.540000      9.000000
25%         1989.000000    497.110000   1179.000000
50%         1996.000000   1223.720000   2769.000000
75%         2002.000000   2741.370000   5595.000000
max         2017.000000  11698.030000  34288.000000



Data Dictionary:
                 Table    Field   Description
count               21       21            21
unique               4       18            19
top     sales_pipeline  account  Company name
freq                 8        2             2



Products:
        sales_price
count      7.000000
mean    6023.571429
std     9388.428070
min       55.000000
25%      823.000000
50%     3393.000000
75%     5151.500000
max    26768.000000



Sales Pipeline:
        close_value
count   6711.000000
mean    1490.915512
std     2320.670773
min        0.000000
25%        0.000000
50%      472.000000
75%     3225.000000
max    30288.000000



Sales Team:
          sales_agent        manager regional_office
count              35             35              35
unique             35              6               3
top     Anna Snelling  Melvin Marxen            East
freq                1              6              12

# Data Pre-Processing

Account Table

In [116]:
acc

             account         sector  year_established  revenue  employees office_location subsidiary_of
0   Acme Corporation      technolgy              1996  1100.04       2822   United States           NaN
1         Betasoloin        medical              1999   251.41        495   United States           NaN
2           Betatech        medical              1986   647.18       1185           Kenya           NaN
3         Bioholding        medical              2012   587.34       1356      Philipines           NaN
4            Bioplex        medical              1991   326.82       1016   United States           NaN
..               ...            ...               ...      ...        ...             ...           ...
80        Zathunicon         retail              2010    71.12        144   United States           NaN
81    Zencorporation      technolgy              2011    40.79        142           China           NaN
82            Zoomit  entertainment              1992   324.19        978   United States           NaN
83           Zotware       software              1979  4478.47      13809   United States           NaN
84          Zumgoity        medical              1984   441.08       1210   United States           NaN

[85 rows x 7 columns]

In [117]:
acc_cols = acc[['account', 'sector', 'office_location', 'subsidiary_of']]

In [118]:
def short_summary(df):
  for columns in df:
      print(f"\n\n\nColumn Name: {df[columns].name}")
      print(df[columns].value_counts())
      print(f"Number of Null values: {df[columns].isnull().sum()}")
      print(f"Dimensions--{df.shape}")

In [119]:
'''for columns in acc_cols:
  print(f"\n\n\nColumn Name: {acc_cols[columns].name}")
  print(f"Number of Null values: {acc_cols[columns].isnull().sum()}")
  print(acc_cols[columns].value_counts())'''
short_summary(acc_cols)

Column Name: account
account
Acme Corporation    1
Betasoloin          1
Betatech            1
Bioholding          1
Bioplex             1
                   ..
Zathunicon          1
Zencorporation      1
Zoomit              1
Zotware             1
Zumgoity            1
Name: count, Length: 85, dtype: int64
Number of Null values: 0
Dimensions--(85, 4)



Column Name: sector
sector
retail                17
technolgy             12
medical               12
marketing              8
finance                8
software               7
entertainment          6
telecommunications     6
services               5
employment             4
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(85, 4)



Column Name: office_location
office_location
United States    71
Kenya             1
Philipines        1
Japan             1
Italy             1
Norway            1
Korea             1
Jordan            1
Brazil            1
Germany           1
Panama            1
Belgium           1
Romania           1
Poland            1
China             1
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(85, 4)



Column Name: subsidiary_of
subsidiary_of
Acme Corporation    4
Sonron              3
Bubba Gump          2
Golddex             2
Inity               2
Massive Dynamic     1
Warephase           1
Name: count, dtype: int64
Number of Null values: 70
Dimensions--(85, 4)

In [120]:
acc.subsidiary_of =  acc.subsidiary_of.fillna('Not a Subsidiary')
acc

             account         sector  year_established  revenue  employees office_location     subsidiary_of
0   Acme Corporation      technolgy              1996  1100.04       2822   United States  Not a Subsidiary
1         Betasoloin        medical              1999   251.41        495   United States  Not a Subsidiary
2           Betatech        medical              1986   647.18       1185           Kenya  Not a Subsidiary
3         Bioholding        medical              2012   587.34       1356      Philipines  Not a Subsidiary
4            Bioplex        medical              1991   326.82       1016   United States  Not a Subsidiary
..               ...            ...               ...      ...        ...             ...               ...
80        Zathunicon         retail              2010    71.12        144   United States  Not a Subsidiary
81    Zencorporation      technolgy              2011    40.79        142           China  Not a Subsidiary
82            Zoomit  entertainment              1992   324.19        978   United States  Not a Subsidiary
83           Zotware       software              1979  4478.47      13809   United States  Not a Subsidiary
84          Zumgoity        medical              1984   441.08       1210   United States  Not a Subsidiary

[85 rows x 7 columns]

Products Table

In [121]:
prdts

          product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768

Sales Pipeline

In [122]:
sales_pipe

     opportunity_id        sales_agent         product  account   deal_stage engage_date  close_date  close_value
0          1C1I7A6R        Moses Frase  GTX Plus Basic  Cancity          Won  2016-10-20  2017-03-01       1054.0
1          Z063OYW0    Darcel Schlecht          GTXPro    Isdom          Won  2016-10-25  2017-03-11       4514.0
2          EC4QE1BX    Darcel Schlecht      MG Special  Cancity          Won  2016-10-25  2017-03-07         50.0
3          MV1LWRNH        Moses Frase       GTX Basic  Codehow          Won  2016-10-25  2017-03-09        588.0
4          PE84CX4O          Zane Levy       GTX Basic   Hatfan          Won  2016-10-25  2017-03-02        517.0
...             ...                ...             ...      ...          ...         ...         ...          ...
8795       9MIWFW5J  Versie Hillebrand     MG Advanced      NaN  Prospecting         NaN         NaN          NaN
8796       6SLKZ8FI  Versie Hillebrand     MG Advanced      NaN  Prospecting         NaN         NaN          NaN
8797       LIB4KUZJ  Versie Hillebrand     MG Advanced      NaN  Prospecting         NaN         NaN          NaN
8798       18IUIUK0  Versie Hillebrand     MG Advanced      NaN  Prospecting         NaN         NaN          NaN
8799       8I5ONXJX  Versie Hillebrand     MG Advanced      NaN  Prospecting         NaN         NaN          NaN

[8800 rows x 8 columns]

In [123]:
sales_pipe_cols = sales_pipe[['sales_agent', 'product', 'account', 'deal_stage']]

In [124]:
'''for values in sales_pipe_cols:
  print(f"\n\n\n{values}")
  print(f"Number of Null values: {sales_pipe_cols[values].isnull().sum()}")
  print(sales_pipe_cols[values].value_counts())'''

short_summary(sales_pipe_cols)

Column Name: sales_agent
sales_agent
Darcel Schlecht       747
Vicki Laflamme        451
Anna Snelling         448
Kary Hendrixson       438
Kami Bicknell         362
Versie Hillebrand     361
Zane Levy             349
Cassey Cress          346
Jonathan Berthelot    345
Gladys Colclough      317
Lajuana Vencill       311
Corliss Cosme         310
Markita Hansen        306
Maureen Marcano       285
Marty Freudenburg     281
Donn Cantrell         275
James Ascencio        267
Violet Mclelland      261
Moses Frase           260
Daniell Hammack       259
Niesha Huffines       239
Reed Clapper          237
Boris Faz             210
Cecily Lampkin        203
Hayden Neloms         202
Elease Gluck          177
Rosalina Dieter       160
Rosie Papadopoulos    160
Garret Kinder         123
Wilburn Farren        110
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(8800, 4)



Column Name: product
product
GTX Basic         1866
MG Special        1651
GTXPro            1480
MG Advanced       1412
GTX Plus Basic    1383
GTX Plus Pro       968
GTK 500             40
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(8800, 4)



Column Name: account
account
Hottechi                 200
Kan-code                 196
Konex                    178
Condax                   170
Dontechi                 129
                        ...
Newex                     55
Bioplex                   53
The New York Inquirer     52
Sumace                    52
Iselectrics               51
Name: count, Length: 85, dtype: int64
Number of Null values: 1425
Dimensions--(8800, 4)



Column Name: deal_stage
deal_stage
Won            4238
Lost           2473
Engaging       1589
Prospecting     500
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(8800, 4)

In [125]:
#Converting date values to date data type, converting from string/object

sales_pipe['close_date'] = pd.to_datetime(sales_pipe['close_date'])
sales_pipe['engage_date'] = pd.to_datetime(sales_pipe['engage_date'])


#Converting Deal stage to factor/category

sales_pipe['deal_satge'] = sales_pipe['deal_stage'].astype('category')

In [126]:
sales_pipe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   datetime64[ns]
 6   close_date      6711 non-null   datetime64[ns]
 7   close_value     6711 non-null   float64
 8   deal_satge      8800 non-null   category
dtypes: category(1), datetime64[ns](2), float64(1), object(5)
memory usage: 558.9+ KB

Null values in Sales Pipe

In [127]:
#inspecting records where account is null/NaN

sales_pipe_null_acc =  sales_pipe[sales_pipe['account'].isnull()]
print(sales_pipe_null_acc)
print(sales_pipe_null_acc['deal_stage'].value_counts())
print(sales_pipe_null_acc.shape)

# deduction:
# null values in account column represent two distinctiv deal stages: Engaging
# and prospecting

     opportunity_id        sales_agent         product account   deal_stage engage_date close_date  close_value   deal_satge
9          HAXMC4IX     James Ascencio     MG Advanced     NaN     Engaging  2016-11-03        NaT          NaN     Engaging
42         EG7OFLFR      Kami Bicknell       GTX Basic     NaN     Engaging  2016-11-14        NaT          NaN     Engaging
44         OLVI7L8M       Cassey Cress          GTXPro     NaN     Engaging  2016-11-16        NaT          NaN     Engaging
56         F5U1ACDD      Kami Bicknell  GTX Plus Basic     NaN     Engaging  2016-11-19        NaT          NaN     Engaging
60         ZZY4516R      Hayden Neloms     MG Advanced     NaN     Engaging  2016-11-20        NaT          NaN     Engaging
...             ...                ...             ...     ...          ...         ...        ...          ...          ...
8795       9MIWFW5J  Versie Hillebrand     MG Advanced     NaN  Prospecting         NaT        NaT          NaN  Prospecting
8796       6SLKZ8FI  Versie Hillebrand     MG Advanced     NaN  Prospecting         NaT        NaT          NaN  Prospecting
8797       LIB4KUZJ  Versie Hillebrand     MG Advanced     NaN  Prospecting         NaT        NaT          NaN  Prospecting
8798       18IUIUK0  Versie Hillebrand     MG Advanced     NaN  Prospecting         NaT        NaT          NaN  Prospecting
8799       8I5ONXJX  Versie Hillebrand     MG Advanced     NaN  Prospecting         NaT        NaT          NaN  Prospecting

[1425 rows x 9 columns]
deal_stage
Engaging       1088
Prospecting     337
Name: count, dtype: int64
(1425, 9)

Dividing sales pipe table in 'Won + Lost', 'Engaging', and 'Prospecting'

In [128]:
# Won+Lost data subset
sales_pipe_labelled = sales_pipe[(sales_pipe['deal_stage'] == 'Won') | (sales_pipe['deal_stage'] == 'Lost')]
print(sales_pipe_labelled)
#print(sales_pipe_labelled['deal_stage'].value_counts())

short_summary(sales_pipe_labelled)

     opportunity_id       sales_agent         product        account deal_stage engage_date close_date  close_value deal_satge
0          1C1I7A6R       Moses Frase  GTX Plus Basic        Cancity        Won  2016-10-20 2017-03-01       1054.0        Won
1          Z063OYW0   Darcel Schlecht          GTXPro          Isdom        Won  2016-10-25 2017-03-11       4514.0        Won
2          EC4QE1BX   Darcel Schlecht      MG Special        Cancity        Won  2016-10-25 2017-03-07         50.0        Won
3          MV1LWRNH       Moses Frase       GTX Basic        Codehow        Won  2016-10-25 2017-03-09        588.0        Won
4          PE84CX4O         Zane Levy       GTX Basic         Hatfan        Won  2016-10-25 2017-03-02        517.0        Won
...             ...               ...             ...            ...        ...         ...        ...          ...        ...
8295       2EBLR9N8   Lajuana Vencill       GTX Basic        Conecom        Won  2017-12-24 2017-12-26        622.0        Won
8296       VDGA4KXA  Violet Mclelland  GTX Plus Basic  Bluth Company        Won  2017-12-24 2017-12-30       1093.0        Won
8297       6WCNNK5J   Maureen Marcano          GTXPro       Hottechi        Won  2017-12-26 2017-12-29       4433.0        Won
8298       YJTQSZ9D  Gladys Colclough  GTX Plus Basic          Inity        Won  2017-12-27 2017-12-30       1052.0        Won
8299       RB8GDYFY  Gladys Colclough      MG Special       Betatech        Won  2017-12-27 2017-12-29         67.0        Won

[6711 rows x 9 columns]



Column Name: opportunity_id
opportunity_id
RB8GDYFY    1
1C1I7A6R    1
Z063OYW0    1
EC4QE1BX    1
MV1LWRNH    1
           ..
S8DX3XOU    1
KWVA7VR1    1
NL3JZH1Z    1
OLK9LKZB    1
7GN8Q4LL    1
Name: count, Length: 6711, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: sales_agent
sales_agent
Darcel Schlecht       553
Vicki Laflamme        347
Anna Snelling         336
Kary Hendrixson       335
Donn Cantrell         275
Kami Bicknell         272
Jonathan Berthelot    264
Versie Hillebrand     264
Zane Levy             261
Cassey Cress          261
Reed Clapper          237
Gladys Colclough      232
Lajuana Vencill       231
Corliss Cosme         229
Markita Hansen        227
Maureen Marcano       213
James Ascencio        206
Moses Frase           195
Marty Freudenburg     194
Violet Mclelland      193
Daniell Hammack       187
Niesha Huffines       175
Cecily Lampkin        160
Boris Faz             153
Hayden Neloms         152
Elease Gluck          126
Garret Kinder         123
Rosie Papadopoulos    121
Rosalina Dieter       110
Wilburn Farren         79
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: product
product
GTX Basic         1436
MG Special        1223
GTXPro            1147
MG Advanced       1084
GTX Plus Basic    1051
GTX Plus Pro       745
GTK 500             25
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: account
account
Hottechi                 193
Kan-code                 187
Konex                    171
Condax                   159
Codehow                  117
                        ...
Bioplex                   46
Plusstrip                 46
The New York Inquirer     44
Sumace                    41
Iselectrics               38
Name: count, Length: 85, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: deal_stage
deal_stage
Won     4238
Lost    2473
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: engage_date
engage_date
2017-07-17    43
2017-04-17    38
2017-04-04    37
2017-04-23    37
2017-10-19    35
              ..
2016-10-30     1
2016-10-29     1
2016-11-18     1
2017-12-23     1
2017-12-26     1
Name: count, Length: 420, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: close_date
close_date
2017-05-22    41
2017-06-11    36
2017-05-26    34
2017-11-19    34
2017-05-20    34
              ..
2017-10-06    12
2017-10-01    12
2017-07-22    11
2017-04-26    10
2017-07-20     5
Name: count, Length: 306, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: close_value
close_value
0.0       2473
54.0        80
53.0        57
57.0        55
59.0        54
          ...
921.0        1
3078.0       1
6456.0       1
5143.0       1
3843.0       1
Name: count, Length: 2051, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)



Column Name: deal_satge
deal_satge
Won            4238
Lost           2473
Engaging          0
Prospecting       0
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(6711, 9)

In [129]:
# Engaging data subset
sales_pipe_engage = sales_pipe[(sales_pipe["deal_stage"])=="Engaging"]
print(sales_pipe_engage)

short_summary(sales_pipe_engage)
print(f"Total engaging records with an account: {sum(sales_pipe_engage['account'].value_counts())}")

     opportunity_id      sales_agent         product    account deal_stage engage_date close_date  close_value deal_satge
9          HAXMC4IX   James Ascencio     MG Advanced        NaN   Engaging  2016-11-03        NaT          NaN   Engaging
25         UP409DSB  Maureen Marcano     MG Advanced  Ganjaflex   Engaging  2016-11-10        NaT          NaN   Engaging
42         EG7OFLFR    Kami Bicknell       GTX Basic        NaN   Engaging  2016-11-14        NaT          NaN   Engaging
44         OLVI7L8M     Cassey Cress          GTXPro        NaN   Engaging  2016-11-16        NaT          NaN   Engaging
56         F5U1ACDD    Kami Bicknell  GTX Plus Basic        NaN   Engaging  2016-11-19        NaT          NaN   Engaging
...             ...              ...             ...        ...        ...         ...        ...          ...        ...
8277       NGTVHTFH        Boris Faz          GTXPro        NaN   Engaging  2017-12-19        NaT          NaN   Engaging
8283       HB740BLB    Hayden Neloms      MG Special      Silis   Engaging  2017-12-20        NaT          NaN   Engaging
8285       HCQK8NQ8   Wilburn Farren  GTX Plus Basic        NaN   Engaging  2017-12-20        NaT          NaN   Engaging
8286       RDHTQLNI     Cassey Cress    GTX Plus Pro        NaN   Engaging  2017-12-21        NaT          NaN   Engaging
8290       DB801ISB     Elease Gluck      MG Special        NaN   Engaging  2017-12-22        NaT          NaN   Engaging

[1589 rows x 9 columns]



Column Name: opportunity_id
opportunity_id
DB801ISB    1
HAXMC4IX    1
UP409DSB    1
EG7OFLFR    1
OLVI7L8M    1
           ..
VDIU10RV    1
GYB4W2AU    1
M7I5O9YU    1
0DRC1U9Q    1
ZZY4516R    1
Name: count, Length: 1589, dtype: int64
Number of Null values: 0
Dimensions--(1589, 9)



Column Name: sales_agent
sales_agent
Vicki Laflamme        104
Kary Hendrixson       103
Kami Bicknell          90
Zane Levy              88
Cassey Cress           85
Darcel Schlecht        83
Corliss Cosme          81
Markita Hansen         79
Maureen Marcano        72
Daniell Hammack        72
Violet Mclelland       68
James Ascencio         61
Anna Snelling          57
Boris Faz              57
Elease Gluck           51
Hayden Neloms          50
Rosalina Dieter        50
Versie Hillebrand      43
Lajuana Vencill        40
Rosie Papadopoulos     39
Gladys Colclough       36
Moses Frase            34
Jonathan Berthelot     33
Marty Freudenburg      33
Wilburn Farren         31
Niesha Huffines        30
Cecily Lampkin         19
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(1589, 9)



Column Name: product
product
GTX Basic         337
MG Special        308
GTX Plus Basic    258
GTXPro            253
MG Advanced       242
GTX Plus Pro      176
GTK 500            15
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(1589, 9)



Column Name: account
account
Betasoloin     12
Zoomit         10
Inity          10
Iselectrics    10
Treequote       9
               ..
Fasehatice      2
Yearin          2
Ron-tech        2
dambase         1
Doncon          1
Name: count, Length: 85, dtype: int64
Number of Null values: 1088
Dimensions--(1589, 9)



Column Name: deal_stage
deal_stage
Engaging    1589
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(1589, 9)



Column Name: engage_date
engage_date
2017-07-22    35
2017-07-27    32
2017-07-30    32
2017-07-25    31
2017-07-21    31
              ..
2017-10-14     1
2017-10-22     1
2017-10-18     1
2017-12-21     1
2017-12-22     1
Name: count, Length: 356, dtype: int64
Number of Null values: 0
Dimensions--(1589, 9)



Column Name: close_date
Series([], Name: count, dtype: int64)
Number of Null values: 1589
Dimensions--(1589, 9)



Column Name: close_value
Series([], Name: count, dtype: int64)
Number of Null values: 1589
Dimensions--(1589, 9)



Column Name: deal_satge
deal_satge
Engaging       1589
Lost              0
Prospecting       0
Won               0
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(1589, 9)
Total engaging records with an account: 501

In [130]:
#Prospecting data subset
#Engaging data subset
sales_pipe_prospect = sales_pipe[(sales_pipe["deal_stage"])=="Prospecting"]
print(sales_pipe_prospect)

short_summary(sales_pipe_prospect)
print(f"Total prospecting records with an account: {sum(sales_pipe_prospect['account'].value_counts())}")

     opportunity_id        sales_agent      product     account   deal_stage engage_date close_date  close_value   deal_satge
8300       6CWZFOHJ      Anna Snelling    GTX Basic  Green-Plus  Prospecting         NaT        NaT          NaN  Prospecting
8301       3LCLVRVV      Anna Snelling    GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8302       YIU1B39V      Anna Snelling    GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8303       8E0VRCLW      Anna Snelling    GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8304       G99CS23F      Anna Snelling    GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
...             ...                ...          ...         ...          ...         ...        ...          ...          ...
8795       9MIWFW5J  Versie Hillebrand  MG Advanced         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8796       6SLKZ8FI  Versie Hillebrand  MG Advanced         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8797       LIB4KUZJ  Versie Hillebrand  MG Advanced         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8798       18IUIUK0  Versie Hillebrand  MG Advanced         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8799       8I5ONXJX  Versie Hillebrand  MG Advanced         NaN  Prospecting         NaT        NaT          NaN  Prospecting

[500 rows x 9 columns]



Column Name: opportunity_id
opportunity_id
8I5ONXJX    1
6CWZFOHJ    1
3LCLVRVV    1
YIU1B39V    1
KAZ72JJ0    1
           ..
YL29KX3L    1
Q9UWOC28    1
GR9S7VHI    1
XRJ54GNR    1
G99CS23F    1
Name: count, Length: 500, dtype: int64
Number of Null values: 0
Dimensions--(500, 9)



Column Name: sales_agent
sales_agent
Darcel Schlecht       111
Anna Snelling          55
Versie Hillebrand      54
Marty Freudenburg      54
Gladys Colclough       49
Jonathan Berthelot     48
Lajuana Vencill        40
Niesha Huffines        34
Moses Frase            31
Cecily Lampkin         24
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(500, 9)



Column Name: product
product
MG Special        120
GTX Basic          93
MG Advanced        86
GTXPro             80
GTX Plus Basic     74
GTX Plus Pro       47
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(500, 9)



Column Name: account
account
Plusstrip      5
Donquadtech    5
Faxquote       5
Plussunin      5
Rundofase      4
              ..
Toughzap       1
Donware        1
Funholding     1
Scottech       1
Golddex        1
Name: count, Length: 73, dtype: int64
Number of Null values: 337
Dimensions--(500, 9)



Column Name: deal_stage
deal_stage
Prospecting    500
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(500, 9)



Column Name: engage_date
Series([], Name: count, dtype: int64)
Number of Null values: 500
Dimensions--(500, 9)



Column Name: close_date
Series([], Name: count, dtype: int64)
Number of Null values: 500
Dimensions--(500, 9)



Column Name: close_value
Series([], Name: count, dtype: int64)
Number of Null values: 500
Dimensions--(500, 9)



Column Name: deal_satge
deal_satge
Prospecting    500
Engaging         0
Lost             0
Won              0
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(500, 9)
Total prospecting records with an account: 163

In [131]:
print(sales_team)
short_summary(sales_team)

           sales_agent           manager regional_office
0        Anna Snelling  Dustin Brinkmann         Central
1       Cecily Lampkin  Dustin Brinkmann         Central
2    Versie Hillebrand  Dustin Brinkmann         Central
3      Lajuana Vencill  Dustin Brinkmann         Central
4          Moses Frase  Dustin Brinkmann         Central
5   Jonathan Berthelot     Melvin Marxen         Central
6    Marty Freudenburg     Melvin Marxen         Central
7     Gladys Colclough     Melvin Marxen         Central
8      Niesha Huffines     Melvin Marxen         Central
9      Darcel Schlecht     Melvin Marxen         Central
10       Mei-Mei Johns     Melvin Marxen         Central
11    Violet Mclelland        Cara Losch            East
12       Corliss Cosme        Cara Losch            East
13  Rosie Papadopoulos        Cara Losch            East
14       Garret Kinder        Cara Losch            East
15      Wilburn Farren        Cara Losch            East
16  Elizabeth Anderson        Cara Losch            East
17     Daniell Hammack     Rocco Neubert            East
18        Cassey Cress     Rocco Neubert            East
19       Donn Cantrell     Rocco Neubert            East
20        Reed Clapper     Rocco Neubert            East
21           Boris Faz     Rocco Neubert            East
22     Natalya Ivanova     Rocco Neubert            East
23      Vicki Laflamme      Celia Rouche            West
24     Rosalina Dieter      Celia Rouche            West
25       Hayden Neloms      Celia Rouche            West
26      Markita Hansen      Celia Rouche            West
27        Elease Gluck      Celia Rouche            West
28      Carol Thompson      Celia Rouche            West
29      James Ascencio     Summer Sewald            West
30     Kary Hendrixson     Summer Sewald            West
31       Kami Bicknell     Summer Sewald            West
32           Zane Levy     Summer Sewald            West
33     Maureen Marcano     Summer Sewald            West
34            Carl Lin     Summer Sewald            West



Column Name: sales_agent
sales_agent
Anna Snelling         1
Cecily Lampkin        1
Versie Hillebrand     1
Lajuana Vencill       1
Moses Frase           1
Jonathan Berthelot    1
Marty Freudenburg     1
Gladys Colclough      1
Niesha Huffines       1
Darcel Schlecht       1
Mei-Mei Johns         1
Violet Mclelland      1
Corliss Cosme         1
Rosie Papadopoulos    1
Garret Kinder         1
Wilburn Farren        1
Elizabeth Anderson    1
Daniell Hammack       1
Cassey Cress          1
Donn Cantrell         1
Reed Clapper          1
Boris Faz             1
Natalya Ivanova       1
Vicki Laflamme        1
Rosalina Dieter       1
Hayden Neloms         1
Markita Hansen        1
Elease Gluck          1
Carol Thompson        1
James Ascencio        1
Kary Hendrixson       1
Kami Bicknell         1
Zane Levy             1
Maureen Marcano       1
Carl Lin              1
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(35, 3)



Column Name: manager
manager
Melvin Marxen       6
Cara Losch          6
Celia Rouche        6
Rocco Neubert       6
Summer Sewald       6
Dustin Brinkmann    5
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(35, 3)



Column Name: regional_office
regional_office
East       12
West       12
Central    11
Name: count, dtype: int64
Number of Null values: 0
Dimensions--(35, 3)

Datasets for further Data Formatting

In [132]:
datasets2 = [('accounts', acc), ('products', prdts),
        ('sales pipeline', sales_pipe), ('sales team', sales_team),
        ('won_lost', sales_pipe_labelled), ('prospect', sales_pipe_prospect),
              ('engaging', sales_pipe_engage)]

In [133]:
for name, dataset in datasets2:
  print(f"\n\n\n*** Dataset: {name.title()} ***")
  print(f"*** Dimensions: {dataset.shape} ***")
  print(f"Info: {dataset.info()}")
  print(f"\n\n\nNull Values in {dataset.isnull().sum()}")
  print(f"\nData view {dataset.head(10)}")

*** Dataset: Accounts ***
*** Dimensions: (85, 7) ***
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   account           85 non-null     object
 1   sector            85 non-null     object
 2   year_established  85 non-null     int64
 3   revenue           85 non-null     float64
 4   employees         85 non-null     int64
 5   office_location   85 non-null     object
 6   subsidiary_of     85 non-null     object
dtypes: float64(1), int64(2), object(4)
memory usage: 4.8+ KB
Info: None



Null Values in account             0
sector              0
year_established    0
revenue             0
employees           0
office_location     0
subsidiary_of       0
dtype: int64

Data view             account         sector  year_established  revenue  employees office_location     subsidiary_of
0  Acme Corporation      technolgy              1996  1100.04       2822   United States  Not a Subsidiary
1        Betasoloin        medical              1999   251.41        495   United States  Not a Subsidiary
2          Betatech        medical              1986   647.18       1185           Kenya  Not a Subsidiary
3        Bioholding        medical              2012   587.34       1356      Philipines  Not a Subsidiary
4           Bioplex        medical              1991   326.82       1016   United States  Not a Subsidiary
5          Blackzim         retail              2009   497.11       1588   United States  Not a Subsidiary
6     Bluth Company      technolgy              1993  1242.32       3027   United States  Acme Corporation
7        Bubba Gump       software              2002   987.39       2253   United States  Not a Subsidiary
8           Cancity         retail              2001   718.62       2448   United States  Not a Subsidiary
9            Cheers  entertainment              1993  4269.90       6472   United States   Massive Dynamic



*** Dataset: Products ***
*** Dimensions: (7, 3) ***
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   product      7 non-null      object
 1   series       7 non-null      object
 2   sales_price  7 non-null      int64
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes
Info: None



Null Values in product        0
series         0
sales_price    0
dtype: int64

Data view           product series  sales_price
0       GTX Basic    GTX          550
1         GTX Pro    GTX         4821
2      MG Special     MG           55
3     MG Advanced     MG         3393
4    GTX Plus Pro    GTX         5482
5  GTX Plus Basic    GTX         1096
6         GTK 500    GTK        26768



*** Dataset: Sales Pipeline ***
*** Dimensions: (8800, 9) ***
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8800 entries, 0 to 8799
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  8800 non-null   object
 1   sales_agent     8800 non-null   object
 2   product         8800 non-null   object
 3   account         7375 non-null   object
 4   deal_stage      8800 non-null   object
 5   engage_date     8300 non-null   datetime64[ns]
 6   close_date      6711 non-null   datetime64[ns]
 7   close_value     6711 non-null   float64
 8   deal_satge      8800 non-null   category
dtypes: category(1), datetime64[ns](2), float64(1), object(5)
memory usage: 558.9+ KB
Info: None



Null Values in opportunity_id       0
sales_agent          0
product              0
account           1425
deal_stage           0
engage_date        500
close_date        2089
close_value       2089
deal_satge           0
dtype: int64

Data view   opportunity_id      sales_agent         product   account deal_stage engage_date close_date  close_value deal_satge
0       1C1I7A6R      Moses Frase  GTX Plus Basic   Cancity        Won  2016-10-20 2017-03-01       1054.0        Won
1       Z063OYW0  Darcel Schlecht          GTXPro     Isdom        Won  2016-10-25 2017-03-11       4514.0        Won
2       EC4QE1BX  Darcel Schlecht      MG Special   Cancity        Won  2016-10-25 2017-03-07         50.0        Won
3       MV1LWRNH      Moses Frase       GTX Basic   Codehow        Won  2016-10-25 2017-03-09        588.0        Won
4       PE84CX4O        Zane Levy       GTX Basic    Hatfan        Won  2016-10-25 2017-03-02        517.0        Won
5       ZNBS69V1    Anna Snelling      MG Special  Ron-tech        Won  2016-10-29 2017-03-01         49.0        Won
6       9ME3374G   Vicki Laflamme      MG Special   J-Texon        Won  2016-10-30 2017-03-02         57.0        Won
7       7GN8Q4LL   Markita Hansen       GTX Basic    Cheers        Won  2016-11-01 2017-03-07        601.0        Won
8       OLK9LKZB  Niesha Huffines  GTX Plus Basic  Zumgoity        Won  2016-11-01 2017-03-03       1026.0        Won
9       HAXMC4IX   James Ascencio     MG Advanced       NaN   Engaging  2016-11-03        NaT          NaN   Engaging



*** Dataset: Sales Team ***
*** Dimensions: (35, 3) ***
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sales_agent      35 non-null     object
 1   manager          35 non-null     object
 2   regional_office  35 non-null     object
dtypes: object(3)
memory usage: 972.0+ bytes
Info: None



Null Values in sales_agent        0
manager            0
regional_office    0
dtype: int64

Data view           sales_agent           manager regional_office
0       Anna Snelling  Dustin Brinkmann         Central
1      Cecily Lampkin  Dustin Brinkmann         Central
2   Versie Hillebrand  Dustin Brinkmann         Central
3     Lajuana Vencill  Dustin Brinkmann         Central
4         Moses Frase  Dustin Brinkmann         Central
5  Jonathan Berthelot     Melvin Marxen         Central
6   Marty Freudenburg     Melvin Marxen         Central
7    Gladys Colclough     Melvin Marxen         Central
8     Niesha Huffines     Melvin Marxen         Central
9     Darcel Schlecht     Melvin Marxen         Central



*** Dataset: Won_Lost ***
*** Dimensions: (6711, 9) ***
<class 'pandas.core.frame.DataFrame'>
Index: 6711 entries, 0 to 8299
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  6711 non-null   object
 1   sales_agent     6711 non-null   object
 2   product         6711 non-null   object
 3   account         6711 non-null   object
 4   deal_stage      6711 non-null   object
 5   engage_date     6711 non-null   datetime64[ns]
 6   close_date      6711 non-null   datetime64[ns]
 7   close_value     6711 non-null   float64
 8   deal_satge      6711 non-null   category
dtypes: category(1), datetime64[ns](2), float64(1), object(5)
memory usage: 478.6+ KB
Info: None



Null Values in opportunity_id    0
sales_agent       0
product           0
account           0
deal_stage        0
engage_date       0
close_date        0
close_value       0
deal_satge        0
dtype: int64

Data view    opportunity_id      sales_agent         product     account deal_stage engage_date close_date  close_value deal_satge
0        1C1I7A6R      Moses Frase  GTX Plus Basic     Cancity        Won  2016-10-20 2017-03-01       1054.0        Won
1        Z063OYW0  Darcel Schlecht          GTXPro       Isdom        Won  2016-10-25 2017-03-11       4514.0        Won
2        EC4QE1BX  Darcel Schlecht      MG Special     Cancity        Won  2016-10-25 2017-03-07         50.0        Won
3        MV1LWRNH      Moses Frase       GTX Basic     Codehow        Won  2016-10-25 2017-03-09        588.0        Won
4        PE84CX4O        Zane Levy       GTX Basic      Hatfan        Won  2016-10-25 2017-03-02        517.0        Won
5        ZNBS69V1    Anna Snelling      MG Special    Ron-tech        Won  2016-10-29 2017-03-01         49.0        Won
6        9ME3374G   Vicki Laflamme      MG Special     J-Texon        Won  2016-10-30 2017-03-02         57.0        Won
7        7GN8Q4LL   Markita Hansen       GTX Basic      Cheers        Won  2016-11-01 2017-03-07        601.0        Won
8        OLK9LKZB  Niesha Huffines  GTX Plus Basic    Zumgoity        Won  2016-11-01 2017-03-03       1026.0        Won
10       NL3JZH1Z    Anna Snelling      MG Special  Bioholding        Won  2016-11-04 2017-03-10         53.0        Won



*** Dataset: Prospect ***
*** Dimensions: (500, 9) ***
<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, 8300 to 8799
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  500 non-null    object
 1   sales_agent     500 non-null    object
 2   product         500 non-null    object
 3   account         163 non-null    object
 4   deal_stage      500 non-null    object
 5   engage_date     0 non-null      datetime64[ns]
 6   close_date      0 non-null      datetime64[ns]
 7   close_value     0 non-null      float64
 8   deal_satge      500 non-null    category
dtypes: category(1), datetime64[ns](2), float64(1), object(5)
memory usage: 35.8+ KB
Info: None



Null Values in opportunity_id      0
sales_agent         0
product             0
account           337
deal_stage          0
engage_date       500
close_date        500
close_value       500
deal_satge          0
dtype: int64

Data view      opportunity_id    sales_agent         product     account   deal_stage engage_date close_date  close_value   deal_satge
8300       6CWZFOHJ  Anna Snelling       GTX Basic  Green-Plus  Prospecting         NaT        NaT          NaN  Prospecting
8301       3LCLVRVV  Anna Snelling       GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8302       YIU1B39V  Anna Snelling       GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8303       8E0VRCLW  Anna Snelling       GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8304       G99CS23F  Anna Snelling       GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8305       XRJ54GNR  Anna Snelling       GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8306       GR9S7VHI  Anna Snelling       GTX Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting
8307       Q9UWOC28  Anna Snelling  GTX Plus Basic   Plusstrip  Prospecting         NaT        NaT          NaN  Prospecting
8308       YL29KX3L  Anna Snelling  GTX Plus Basic    Zumgoity  Prospecting         NaT        NaT          NaN  Prospecting
8309       OJDZN6UK  Anna Snelling  GTX Plus Basic         NaN  Prospecting         NaT        NaT          NaN  Prospecting



*** Dataset: Engaging ***
*** Dimensions: (1589, 9) ***
<class 'pandas.core.frame.DataFrame'>
Index: 1589 entries, 9 to 8290
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   opportunity_id  1589 non-null   object
 1   sales_agent     1589 non-null   object
 2   product         1589 non-null   object
 3   account         501 non-null    object
 4   deal_stage      1589 non-null   object
 5   engage_date     1589 non-null   datetime64[ns]
 6   close_date      0 non-null      datetime64[ns]
 7   close_value     0 non-null      float64
 8   deal_satge      1589 non-null   category
dtypes: category(1), datetime64[ns](2), float64(1), object(5)
memory usage: 113.5+ KB
Info: None



Null Values in opportunity_id       0
sales_agent          0
product              0
account           1088
deal_stage           0
engage_date          0
close_date        1589
close_value       1589
deal_satge           0
dtype: int64

Data view    opportunity_id      sales_agent         product     account deal_stage engage_date close_date  close_value deal_satge
9        HAXMC4IX   James Ascencio     MG Advanced         NaN   Engaging  2016-11-03        NaT          NaN   Engaging
25       UP409DSB  Maureen Marcano     MG Advanced   Ganjaflex   Engaging  2016-11-10        NaT          NaN   Engaging
42       EG7OFLFR    Kami Bicknell       GTX Basic         NaN   Engaging  2016-11-14        NaT          NaN   Engaging
44       OLVI7L8M     Cassey Cress          GTXPro         NaN   Engaging  2016-11-16        NaT          NaN   Engaging
56       F5U1ACDD    Kami Bicknell  GTX Plus Basic         NaN   Engaging  2016-11-19        NaT          NaN   Engaging
60       ZZY4516R    Hayden Neloms     MG Advanced         NaN   Engaging  2016-11-20        NaT          NaN   Engaging
64       0DRC1U9Q  Maureen Marcano       GTX Basic  Green-Plus   Engaging  2016-11-20        NaT          NaN   Engaging
79       M7I5O9YU    Corliss Cosme       GTX Basic      Cheers   Engaging  2016-11-23        NaT          NaN   Engaging
82       GYB4W2AU     Elease Gluck     MG Advanced         NaN   Engaging  2016-11-23        NaT          NaN   Engaging
85       VDIU10RV   Markita Hansen      MG Special  Lexiqvolax   Engaging  2016-11-23        NaT          NaN   Engaging

In [143]:
#Checking duplicates in each dataframe

def dup_check (df):
  for name, dataset in df:
    print(f"\n\n\n{name.title()}:")
    print(f"{dataset.duplicated().sum()}")


dup_check(datasets2)

Accounts:
0



Products:
0



Sales Pipeline:
0



Sales Team:
0



Won_Lost:
0



Prospect:
0



Engaging:
0